# Generated by Django 4.2.1 on 2023-06-02 10:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('book', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='book',
            old_name='id_in_shop',
            new_name='id_in_store',
        ),
    ]
