version: "3"

services:
  store_db:
    container_name: store_db
    image: postgres:latest
    restart: always
    env_file:
      - store.env
    expose:
      - 5432
    volumes:
      - store_db_volume:/var/lib/postgresql/data
    networks:
      - store_db_network

  shop_db:
    container_name: shop_db
    image: postgres:latest
    restart: always
    env_file:
      - shop.env
    expose:
      - 5432
    volumes:
      - shop_db_volume:/var/lib/postgresql/data
    networks:
      - shop_db_network

  store:
    container_name: store
    build:
      context: .
      dockerfile: docker/store/Dockerfile
    env_file:
      - store.env
    command: sh runserver.sh
    volumes:
      - ./store:/app
    ports:
      - "8000:8000"
    depends_on:
      - store_db
    networks:
      - store_db_network
    restart: on-failure

  shop:
    container_name: shop
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
    env_file:
      - shop.env
    command: sh runserver.sh
    volumes:
      - ./shop:/app
    ports:
      - "8001:8000"
    depends_on:
      - shop_db
    networks:
      - shop_db_network
    restart: on-failure


  redis:
    container_name: redis
    image: redis:6.2.1-alpine
    restart: on-failure
    networks:
      - celery
    expose:
      - 6379


  rabbitmq:
    container_name: rabbitmq
    image: rabbitmq:3-alpine
    restart: on-failure
    networks:
      - shop_db_network
    expose:
      - 4369
      - 5671
      - 5672
      - 15672
      - 25672

  celery:
    container_name: celery
    build:
      context: .
      dockerfile: docker/shop/Dockerfile
    env_file:
      - shop.env
    depends_on:
      - rabbitmq
      - redis
      - shop
      - store
      - shop_db
      - store_db
    expose: []
    networks:
      - celery
      - store_db_network
      - shop_db_network
    restart: on-failure
    command: celery -A core worker -B -l INFO

volumes:
  store_db_volume:
  shop_db_volume:

networks:
  store_db_network:
  shop_db_network:
  celery: