version: "3"

services:
  store_db:
    container_name: store_db
    image: postgres:latest
    restart: always
    env_file:
      - store.env
    expose:
      - "5432:5432"
    volumes:
      - store_db_volume:/var/lib/postgresql/data
    networks:
      - store_db_network

  store:
    container_name: store
    build:
      context: .
      dockerfile: docker/store/Dockerfile
    env_file:
      - store.env
    command: sh runserver.sh
    volumes:
      - ./store:/app
    ports:
      - "8000:8000"
    depends_on:
      - store_db
    networks:
      - store_db_network
    restart: on-failure
    healthcheck:
      test: [ "CMD", "curl", "--fail", "http://0.0.0.0:8000/admin/login/" ]
      interval: 1m
      timeout: 5s
      retries: 2

volumes:
  store_db_volume:

networks:
  store_db_network: