# Generated by Django 4.2.1 on 2023-06-11 20:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('order', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='status',
            field=models.PositiveSmallIntegerField(choices=[(2, 'Order'), (3, 'Success'), (4, 'Fail')]),
        ),
    ]
